title: Helmet
short_description: Express.js security with HTTP headers
description: Helmet helps you secure your Express.js apps by setting various HTTP headers. It's not a silver bullet, but it can help!
helmet_version: "6.0.0"
baseurl: ""
url: "https://helmetjs.github.io"

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "FOOTNOTES"]
